version: '3'
services:
  account-services:
    build:
      context: ./account.services
    ports:
      - '5001:5000'
    depends_on:
      - rabbitmq

  api-gateway:
    build:
      context: ./api_gateway
    ports:
      - '5000:5000'
    depends_on:
      - account-services
      - profile-services

  profile-services:
    build:
      context: ./profile.services
    ports:
      - '5002:5000'
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    
   
